[tool.poetry]
name = "azely"
version = "0.4.2"
description = "Python package for calculation and plotting of astronomical object's azimuth/elevation"
authors = ["Akio Taniguchi <taniguchi@a.phys.nagoya-u.ac.jp>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
astropy = "^4.0"
dataclasses = { version = "^0.7", python = "~3.6" }
docopt = "^0.6.2"
geopy = "^1.21.0"
matplotlib = "^3.1.3"
numpy = "^1.17.5"
pandas = ">= 0.25.0, < 1.1.0"
python-dateutil = "^2.6.1"
pytz = ">= 2018.9, < 2020.0"
requests = "^2.21.0"
timezonefinder = "^4.2.0"
toml = "^0.10.0"

[tool.poetry.dev-dependencies]
black = "^19.10b0"
flake8 = "^3.7.9"
ipython = "^7.12.0"
jupyter = "^1.0.0"
jupyterlab = "^1.2.6"
pytest = "^5.3.5"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
