[tool.poetry]
name = "azely"
version = "0.5.2"
description = "Computation and plotting of astronomical object's azimuth/elevation"
authors = ["Akio Taniguchi <taniguchi@a.phys.nagoya-u.ac.jp>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/astropenguin/azely"
documentation = "https://astropenguin.github.io/azely"

[tool.poetry.dependencies]
python = "^3.6"
astropy = "^4.0"
dataclasses = { version = "^0.7", python = "~3.6" }
geopy = "^1.23"
matplotlib = "^3.2"
numpy = "^1.18"
pandas = ">= 0.25"
python-dateutil = "^2.8"
pytz = ">= 2018.9"
requests = "^2.23"
timezonefinder = "^4.4"
toml = "^0.10"

[tool.poetry.dev-dependencies]
black = "^19.10b0"
flake8 = "^3.8"
ipython = "^7.16"
jupyterlab = "^2.2"
pytest = "^6.0"
sphinx = "^3.1"
sphinx-rtd-theme = "^0.5"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
